### ISSUE TITLE
Parser crashing when the program is not terminated with a newline

### ISSUE THREAD

**Issue by pavelvelikhov** [pavelvelikhov/pythonql#11]
If the program is not terminated with a newline, the parser crashes with an error:
```
#coding: pythonql

print([ select y for x in [1,2,3] let y = x**2 ])
```

C:\Python\Scripts\PythonQL>python testPQL.py
'NoneType' object has no attribute 'lineno'
  File "testPQL.py", line 1
SyntaxError: encoding problem: pythonql

**Comment by pavelvelikhov** [comment]
Seems to be fixed

**Comment by pavelvelikhov** [comment]
Need to test this

**Comment by pavelvelikhov** [comment]
Solved in upcoming release

**Comment by yoyomolinas** [comment]
Hi, 

I still have the same issue. I'm using Python  3.6.7 Anaconda distribution. Is there a particular way to upgrade the package, other than `pip install --upgrade pythonql3` @pavelvelikhov ?

Thanks,

**Comment by pavelvelikhov** [comment]
Hi,

  Let me look into this over the next few days, was a bit busy

Best regards,
Pavel

P.S. Don’t know another way to upgrade the package, you could uninstall and install again, but that should be equivalent

**Comment by cubicapple** [comment]
same problem with 'NoneType' object has no attribute 'lineno' without a newline at the end of the file. Fresh install from github clone

**Comment by pavelvelikhov** [comment]
> 
> 
> same problem with 'NoneType' object has no attribute 'lineno' without a newline at the end of the file. Fresh install from github clone

Can you give me more details for your installation, I cannot replicate the error

**Comment by cubicapple** [comment]
It's a WSL with vanilla setup and pythonql installed from github clone:

cubic@BlackDell:/mnt/c/Users/cubic/lab/pythonql$ uname -a
Linux BlackDell 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC
2020 x86_64 x86_64 x86_64 GNU/Linux
cubic@BlackDell:/mnt/c/Users/cubic/lab/pythonql$ python --version
Python 3.8.5
cubic@BlackDell:/mnt/c/Users/cubic/lab/pythonql$ git config --get
remote.origin.url
https://github.com/pythonql/pythonql.git
cubic@BlackDell:/mnt/c/Users/cubic/lab/pythonql$ pip list | grep pythonql
pythonql3              0.9.71
cubic@BlackDell:/mnt/c/Users/cubic/lab/pythonql$
